### mockoon api
@api_url=http://localhost:3001/api/v1

### TODO register
POST {{api_url}}/auth/register
Content-Type: application/json

{
    "name":"name",
    "email":"email",
    "password":"password"
}

### TODO login
POST {{api_url}}/auth/login
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"test!31"
}

### TODO user info
GET {{api_url}}/auth/me
Authorization: Bearer jwt

### user info 
GET {{api_url}}/user/1
# Authorization: Bearer jwt

### list rentals
GET {{api_url}}/rentals
Authorization: Bearer jwt


### one rental
GET {{api_url}}/rentals/1
Authorization: Bearer jwt

### insert rental
POST {{api_url}}/rentals
Authorization: Bearer jwt
Content-Type: application/json

{
    "name":"hAPI ",
    "surface": 97,
    "price": 99999.97,
    "picture":"https://picsum.photos/seed/hapi/200/300",
    "description":"maison d'APIculteur",
    "owner_id":1
}

### TODO update rental
PUT {{api_url}}/rentals/1
Authorization: Bearer jwt
Content-Type: application/json

{
    "name":"villa à la playa"
}

### update rental
PUT {{api_url}}/rentals/1
Authorization: Bearer jwt
Content-Type: application/json

{
    "name":"villa à la plage"
}

### sends a message
POST {{api_url}}/messages
Content-Type: application/json
# Authorization: Bearer jwt

{
    "writer_id":"1",
    "message":"j'ai vu des lAPIns",
    "rental_id":"3"
}
