### mockoon api
@api_url=http://localhost:3001/api/v1
@jwt_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJncmVnQGdyZWcuZnIiLCJpYXQiOjE3Nzk4NjcxNDAsImV4cCI6MTc3OTg3MDc0MH0.JYfh415pKyf4MzQYCLQ5hGmju36ur2N-rUu0bbI8ky8


# ### register
# POST {{api_url}}/auth/register
# Content-Type: application/json

# {
#     "name":"name",
#     "email":"email",
#     "password":"password"
# }

### login
POST {{api_url}}/auth/login
Content-Type: application/json

{
    "email":"greg@greg.fr",
    "password":"greg"
}

### user info
GET {{api_url}}/auth/me
Authorization: Bearer {{jwt_token}}

### user info 
GET {{api_url}}/user/20
Authorization: Bearer {{jwt_token}}

### list rentals
GET {{api_url}}/rentals
Authorization: Bearer {{jwt_token}}


### one rental
GET {{api_url}}/rentals/1
Authorization: Bearer {{jwt_token}}

### insert rental
POST {{api_url}}/rentals
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
    "name":"hAPI ",
    "surface": 97,
    "price": 99999.97,
    "picture":"https://picsum.photos/seed/hapi/200/300",
    "description":"maison d'APIculteur",
    "owner_id":1
}

### TODO update rental
PUT {{api_url}}/rentals/1
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
    "name":"villa à l'API"
}

# ### update rental
# PUT {{api_url}}/rentals/1
# Authorization: Bearer {{jwt_token}}
# Content-Type: application/json

# {
#     "name":"villa à la plage"
# }

### sends a message
POST {{api_url}}/messages
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "writer_id":"1",
    "message":"j'ai vu des lAPIns",
    "rental_id":"3"
}
