### mockoon api
@api_url=http://localhost:3001/api/user
@jwt_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJncmVnQGdyZWcuZnIiLCJpYXQiOjE3Nzk5NjUzMDgsImV4cCI6MTc4MDAwMTMwOH0.sRZwShQDXUOmzjvBqTkLW8ChwOjPQ1q31B5lb7l6AxQ

@jwt_invalid_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJncmVnQGdyZWcuZnIiLCJpYXQiOjE3Nzk4NzYyMDYsImV4cCI6MTc3OTg3NjIwNn0.HgOviu53ukTxZgySDdX8vzEZ7UVcL2bEo4SXGMuN67M

### SECURED

GET {{api_url}}/1
Authorization: Bearer {{jwt_invalid_token}}

### user info 
GET {{api_url}}/1
Authorization: Bearer {{jwt_token}}

### ERRORS ###


### TODO user info NOT FOUND => 404
GET {{api_url}}/0
Authorization: Bearer {{jwt_token}}

### user id not valid => 400
GET {{api_url}}/toto
Authorization: Bearer {{jwt_token}}