### mockoon api
@api_url=http://localhost:3001/api

### TODO register missing info
POST {{api_url}}/auth/register
Content-Type: application/json

{
    "name":"name",
    "email":"email",
    "password":"password"
}

### TODO login wrong email
### TODO login wrong password
POST {{api_url}}/auth/login
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"test!31"
}

### TODO user info
GET {{api_url}}/auth/me
Authorization: Bearer jwt

### TODO user info NOT FOUND => 404
GET {{api_url}}/user/0
# Authorization: Bearer jwt

### user id not valid => 400
GET {{api_url}}/user/toto
# Authorization: Bearer jwt


### TODO not found rental => 404
GET {{api_url}}/rentals/0
Authorization: Bearer jwt

### rental_id not valid  => 400
GET {{api_url}}/rentals/toto
Authorization: Bearer jwt


### TODO insert rental - missing data => 400
### TODO insert rental - owner not found => 404
POST {{api_url}}/rentals
Authorization: Bearer jwt
Content-Type: application/json

{
    "name":"hAPI ",
    "surface": 97,
    "price": 99999.97,
    "picture":"https://picsum.photos/seed/hapi/200/300",
    "description":"maison d'APIculteur",
    "owner_id":1
}

### TODO insert rental - data missing => 400
PUT {{api_url}}/rentals/1
Authorization: Bearer jwt
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"test!31"
}

### TODO sends a message - data missing => 400
POST {{api_url}}/messages
Content-Type: application/json
# Authorization: Bearer jwt

{
    "user_id":"pour",
    "message":"my message",
    "rental_id":"123"
}
