
### register
POST http://localhost:3001/api/v1/auth/register
Content-Type: application/json

{
    "email" : "greg@greg.fr",
    "name" : "greg API",
    "password" : "greg"
}
### login
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "email" : "greg@greg.fr",
    "password" : "greg"
}

### login failed
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "email" : "greg@greg.fr",
    "password" : "failed"
}
