@token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTc3OTQ2NDI3OSwiaWF0IjoxNzc5Mzc3ODc5fQ.mNdfSJmAEBMFAYkmijcX-CIUI3RMwMvJpOdH7mnvkxw

### register
POST http://localhost:3001/api/v1/register
Content-Type: application/json

{
    "email" : "greg@greg.fr",
    "name" : "greg API",
    "password" : "greg"
}
### login
POST http://localhost:3001/api/v1/login
Content-Type: application/json

{
    "email" : "greg@greg.fr",
    "password" : "greg"
}

### login failed
POST http://localhost:3001/api/v1/login
Content-Type: application/json

{
    "email" : "greg@greg.fr",
    "password" : "failed"
}

### ressources
GET http://localhost:3001/api/v1/rentals
Authorization: Bearer {{token}}
